# Generated by Django 2.2.6 on 2019-12-05 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_remove_profile_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ig_url',
            new_name='instagram',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
